[package]
name = "ilp-packet"
version = "0.2.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "ILP packet (de)serializer library"
license = "Apache-2.0"

[dependencies]
base64 = "0.6.0"
byteorder = "1.0.0"
quick-error = "1.2.0"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
