[package]
name = "ilp"
version = "0.3.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"

[dependencies]
base64 = "0.10.0"
byteorder = "1.2.7"
bytes = "0.4.10"
chrono = "0.4.6"
clap = "2.32.0"
env_logger = "0.5.13"
failure = "0.1.3"
failure_derive = "0.1.3"
futures = "0.1.25"
hex = "0.3.2"
hyper = "0.12.13"
lazy_static = "1.1.0"
log = "0.4.6"
num-bigint = "0.2.0"
num-traits = "0.2.6"
quick-error = "1.2.2"
ring = "0.13.2"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
tokio = "0.1.11"
tokio-io = "0.1.10"
tokio-tungstenite = { git = "https://github.com/emschwartz/tokio-tungstenite" }
tokio-tcp = "0.1.2"
tungstenite = { git = "https://github.com/emschwartz/tungstenite-rs" }
url = "1.7.1"
