[package]
name = "ilp-packet"
version = "0.2.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "ILP packet (de)serializer library"
license = "Apache-2.0"

[dependencies]
byteorder = "1.0.0"
chrono = { path = "../chrono" }
hex = "0.3.2"
lazy_static = "1.0.1"
quick-error = "1.2.0"