version: 2
jobs:
  style-and-audit:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    steps:
      - checkout
      - run:
          name: Install Cargo Extensions
          command: |
            cargo install --quiet cargo-audit || true # cargo-kcov
            rustup component add rustfmt clippy || true
      - run:
          name: cargo fmt
          command: |
            cargo fmt --all -- --check
      - run:
          name: cargo clippy
          command: |
            cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: cargo audit
          command: cargo audit

  build-test:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    # TODO try even larger box, maybe we can speed it up and avoid needing to reduce the codegen units
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Reduce codegen units
          # If we don't include this, the linker runs out of memory when building
          # the project on CI. We don't include this normally though because
          # it should be able to build with more units on other machines
          command: printf "[profile.dev]\ncodegen-units = 1\n" >> Cargo.toml
      - run:
          name: Build
          command: cargo build --all-features --all-targets
      - run:
          name: Install Redis
          command: |
            # TODO is this update needed?
            sudo apt-get update
            sudo apt-get install redis-server
            redis-server --version
      - run:
          name: Test
          # Note the timeout is included to make sure that they
          # do not run for more than 10 minutes under any circumstances
          # (We have had issues with bugs causing the tests to "run"
          # for 5 hours, wasting a ton of compute credits)
          command: timeout 10m cargo test --all --all-features
          environment:
            RUST_BACKTRACE: "1"

workflows:
  version: 2
  build-test-check:
    jobs:
      - style-and-audit
      - build-test
