[package]
name = "interledger-ildcp"
version = "0.2.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Implementation of the Interledger Dynamic Configuration Protocol (ILDCP)"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.4.12"
byteorder = "1.3.1"
futures = "0.1.25"
interledger-packet = { path = "../interledger-packet", version = "0.1.0" }
interledger-service = { path = "../interledger-service", version = "0.2.0" }
lazy_static = "1.3.0"
log = "0.4.6"
